FROM node:18 AS build

WORKDIR /app

ARG REACT_APP_PROD
ENV REACT_APP_PROD=$REACT_APP_PROD

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
